{{- $fullname := include "rocketmq.fullname" . -}}
{{- $ns := .Release.Namespace }}
{{- $labels := ( include "rocketmq.labels" . | fromYaml ) }}

{{- $_tmp := dict "namesrvs" list -}}

{{- range $idx := ( until ( .Values.namesrv.replicaCount | int ) ) -}}
 {{- $_x := printf "%s-namesrv-%s.%s-namesrv-headless:9876" $fullname (toString $idx) $fullname }}
 {{- $_ := set $_tmp "namesrvs" ( append $_tmp.namesrvs $_x ) -}}
{{- end }}

{{- $namesrv_addrs := join ";" $_tmp.namesrvs -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rocketmq.fullname" . }}-console
  labels:
    {{- include "rocketmq.labels" $ | nindent 4 }}
    rocketmq.role: console
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      {{- include "rocketmq.labels" $ | nindent 6 }}
      rocketmq.role: console
  template:
    metadata:
      labels:
        {{- include "rocketmq.labels" $ | nindent 8 }}
        rocketmq.role: console
    spec:
      containers:
      - name: rocketmq-console
        image: {{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}
        imagePullPolicy: {{ .Values.console.image.pullPolicy }}
        {{- with .Values.console.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
          - name: JAVA_OPTS
            value: "-Drocketmq.namesrv.addr={{ $namesrv_addrs }} -Dcom.rocketmq.sendMessageWithVIPChannel=false -Duser.timezone=GMT+8"