apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-console
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
    rocketmq.role: console
  {{- with .Values.console.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }} 
spec:
  type: {{ .Values.console.service.type }}
  ports:
    - port: {{ .Values.console.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    rocketmq.role: console
