apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-namesrv
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
    rocketmq.role: namesrv
  {{- with .Values.namesrv.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }} 
spec:
  type: {{ .Values.namesrv.service.type }}
  ports:
    - port: {{ .Values.namesrv.service.port }}
      targetPort: namesrv
      protocol: TCP
      name: namesrv
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    rocketmq.role: namesrv
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-namesrv-headless
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
    rocketmq.role: namesrv
  {{- with .Values.namesrv.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }} 
spec:
  type: {{ .Values.namesrv.service.type }}
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.namesrv.service.port }}
      targetPort: namesrv
      protocol: TCP
      name: namesrv
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    rocketmq.role: namesrv
